version: '3'
services:
  storefront:
    environment:
      - BASE_URL_API_BROWSER=http://bbt-online.ru
      - BASE_URL_API=http://backend:8000
      - BASE_URL=http://bbt-online.ru
    depends_on:
      - backend
    image: bbtrust/storefront
    command: npm run prod

  backend:
    environment:
      - DB_CONNECTION=postgresql://bbtadm:bbtpass@postgres/bbt
      - PORT=8000
      - DOWNLOADS_PATH=/downloads
      - SMTP_HOST=smtp
      - SMTP_PORT=1025
    volumes:
      - ./downloads:/downloads
    depends_on:
      - smtp
      - postgres
    expose:
      - 8000
    image: bbtrust/backend

  smtp:
    image: namshi/smtp
    ports:
      - 1025:1025
    expose:
     - 1205
    environment:
      - PORT=1025
      - GMAIL_USER=
      - GMAIL_PASSWORD=

  nginx:
    ports:
      - 80:80
      - 443:443
    environment:
     - NGINX_PORT=80
     - ENV=prod
    depends_on:
     - backend
     - storefront
    volumes:
     - /etc/letsencrypt:/etc/letsencrypt:ro
    image: bbtrust/nginx

  postgres:
    # todo: do not expose port to the whole world
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: bbtpass
      POSTGRES_USER: bbtadm
      POSTGRES_DB: bbt
    volumes:
      - ./db:/var/lib/postgresql/data
