version: '3'
services:
  storefront:
    stdin_open: true
    tty: true
    volumes:
      - ./src/storefront:/app

  backend:
    restart: always
    stdin_open: true
    tty: true
    volumes:
      - ./src/backend:/app
