name: Python application

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: bbtpass
          POSTGRES_USER: bbtadm
          POSTGRES_DB: bbt
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      working-directory: ./src/backend
      run: |
        pip install poetry
        poetry install
    - name: pylint
      working-directory: ./src/backend
      run: |
        poetry run pylint **.py
    - name: mypy
      working-directory: ./src/backend
      run: |
        poetry run mypy .
    - name: pycodestyle
      working-directory: ./src/backend
      run: |
        poetry run pycodestyle . --max-line-length=90 --exclude=alembic
    - name: migrations
      working-directory: ./src/backend
      run: |
        poetry run alembic upgrade head
    - name: tests
      working-directory: ./src/backend
      env:
        DO_NOT_SEND_EMAIL: 1
      run: |
        poetry run python3 -m pytest
